### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by dtroxey**
Playing with basic editing of major text and deleting information session box

### CODE REVIEW

**Comment by wamoyo** [comment]
@dtroxey What are you doing in this dark, dingy corner of the web? : )

**Comment by dtroxey** [comment]
@wamoyo Hopefully taking over the world

**Comment by wamoyo** [comment]
Your changes are up by the way: https://apply.hub.ki/carboncapture/

**Comment by wamoyo** [comment]
I can teach you how to make and view changes locally too if you want.

**Comment by andyburnett** [comment]
Morning,
I don’t know if your responses go to Donnalyn. You might want to slack her, rather than reply to commits.

**Pull request merged**
